# Project information
site_name: OpenSourceTest V0.2.0 Docs
site_description: OpenSourceTest V0.2.0 User Documention
site_author: "chineseluo"
# site_favicon need a picture path
site_favicon: ""

# Repository
repo_name: OpenSourceTest
repo_url: https://github.com/chineseluo/opensourcetest

# Copyright
copyright: 'Copyright &copy; 2020 - 2021 chineseluo; 蜀ICP备2020034353号-1'

# Configuration
theme:
    name: 'material'
    language: 'zh'
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

# Google Analytics
google_analytics: ['UA-36723568-3', 'auto']

# Markdown syntax extensions,mkdocs-plugin
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
    - Introduction: index.md
    - Installation: installation.md
    - Http User Guide:
          - Scaffold: httpuserguide/scaffold.md
          - Write Testcase: httpuserguide/write_testcase.md
          - Ost Source: httpuserguide/ost_source.md
          - Ost Plugin: httpuserguide/ost_plugin.md
          - Run Testcase: httpuserguide/run_testcase.md
          - Testing Report: httpuserguide/testing_report.md
    - UI User Guide:
          - Scaffold: uiuserguide/scaffold.md
          - Write Testcase: uiuserguide/write_testcase.md
          - Ost Source: uiuserguide/ost_source.md
          - Ost Plugin: uiuserguide/ost_plugin.md
          - Run Testcase: uiuserguide/run_testcase.md
          - Testing Report: uiuserguide/testing_report.md
    - Sponsors: sponsors.md
    - Changelog: changelog.md