allure_environment:
  URL: https://github.com/chineseluo/opensourcetest
  description: "阿木木的UI自动化测试框架"
  username: 848257135@qq.com
  version: V0.2.0

test_info:
  test_URL: https://getsuwo.com/?n=fastCat.fcFrontSnail.NewFront.NewFront.PCLoginPage